---
- name: apt install apt-transport-https
  apt:
    name: apt-transport-https
    update_cache: yes
    
- name: download apt-key.gpg
  shell: curl https://mirrors.aliyun.com/kubernetes/apt/doc/apt-key.gpg | apt-key add - 

- name: add kubernetes sources
  shell: |
    cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
    deb https://mirrors.aliyun.com/kubernetes/apt/ kubernetes-xenial main
    EOF

- name: apt install kubeadm
  apt:
    name: "{{item}}"
    update_cache: yes
  with_items:
    - "kubeadm={{kubeadm_install_version}}"
    - "kubelet={{kubeadm_install_version}}"  
    - "kubectl={{kubeadm_install_version}}"

